config/routes.rb
BreakableToy::Application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

  resources :quizzes do
    resources :questions
    resources :submissions
  end

  resources :questions do
    resources :question_choices
  end

  resources :question_choices do
    resources :answer
  end

  resources :submissions do
    resources :answers
  end

  root 'welcome#index'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question,
    inverse_of: :answers
  belongs_to :submission,
    inverse_of: :answers
  belongs_to :question_choice,
    inverse_of: :answer

  validates_presence_of :question_choice
  validates_presence_of :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quiz,
    inverse_of: :questions
  has_many :answers,
    inverse_of: :question
  has_many :question_choices,
    inverse_of: :question,
    :dependent => :destroy
  has_many :submissions,
    through: :answers
  accepts_nested_attributes_for :question_choices, 
    :reject_if => lambda { |a| a[:option].blank? },
    allow_destroy: true
  accepts_nested_attributes_for :answers,
    :reject_if => lambda { |a| a[:option].blank? },
    allow_destroy: true

  validates_presence_of :name
end

app/models/question_choice.rb
class QuestionChoice < ActiveRecord::Base
  belongs_to :question,
    inverse_of: :question_choices
  has_one :answer,
    inverse_of: :question_choice
  accepts_nested_attributes_for :answer, allow_destroy: true
  
  validates_presence_of :option
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :quizzes
  has_many :submissions,
    inverse_of: :quiz,
    :dependent => :destroy
  has_many :questions,
    inverse_of: :quiz,
    :dependent => :destroy
  accepts_nested_attributes_for :questions,
    :reject_if => lambda { |a| a[:name].blank? },
    allow_destroy: true
  accepts_nested_attributes_for :submissions,
    :reject_if => lambda { |a| a[:name].blank? },
    allow_destroy: true

  validates_presence_of :title
  validates_presence_of :user
  validates_presence_of :age_rating

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :submissions
  belongs_to :quiz,
    inverse_of: :submissions
  has_many :answers,
    inverse_of: :submission
  accepts_nested_attributes_for :answers

  before_save :user_score

  def user_score
    @answers = self.answers
    count = @answers.length
    initial_result = 0
    @answers.each do |a|
      if a.question_choice.correct == true
        initial_result += 1
      end
    end
    calculated_result = (initial_result.to_f/count.to_f)*100.0
    self.result = calculated_result.round(2)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :quizzes,
    inverse_of: :user
  has_many :submissions,
    inverse_of: :user

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :username

  validates_numericality_of :age
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_devise_params, if: :devise_controller?

  protected
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :username, :age, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @q = Quiz.search(params[:q])
    @quizzes = @q.result(distinct: true)
  end

  def new
    @quiz = Quiz.new
      question = @quiz.questions.build
      2.times { question.question_choices.build }
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.user = current_user
    if @quiz.save
      flash[:notice] = "Quiz created successfully"
      redirect_to quiz_path(@quiz)
    else
      flash[:notice] = "Please fill in blank fields"
      redirect_to new_quiz_path
    end
  end

  def show
    @quiz = Quiz.find(params[:id])
    @submission = @quiz.submissions.build
    @submission.answers.build
  end

  protected
  def quiz_params
    params.require(:quiz).permit(:title, :age_rating, :private,
      :question, questions_attributes:
        [:name, question_choices_attributes:[:option, :correct]],
        submissions_attributes: [:result])
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :authenticate_user!

  def new
    @submission = Submission.new
    @answers = @submission.answers.build
  end

  def create
    @quiz = Quiz.find(params[:quiz_id])
    @submission = @quiz.submissions.new(submission_params)
    @submission.user = current_user

    if @submission.save
      redirect_to submission_path(@submission),
        notice: "Quiz taken! You got a #{@submission.result}%!"
    else
      redirect_to quiz_path(@quiz)  
    end
  end

  def show
    @submission = Submission.find(params[:id])
    @quiz = @submission.quiz
  end

  protected
  def submission_params
    params.require(:submission).permit(:result, :answers_attributes => [:question_id, :question_choice_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    # creates a new instance of QuestionChoice
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

  def gravatar_url(user, size)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=" + size
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz Me</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="row-fluid">
  <div class='navbar'>
    <div class='navbar-inner'>
      <ul class='nav pull-left'>
        <li class="<%= 'active' if current_page?(root_path) %>">
          <%= link_to image_tag('https://lh5.googleusercontent.com/-OzkTTMhg9ho/UmEwMPEuhGI/AAAAAAAAAkY/2QUZxf-mRIY/w167-h176-no/q.png', size: '20x20'), root_path %>
        </li>
        <li class="<%= 'active' if current_page?(new_quiz_path) %>">
          <%= link_to 'Create A Quiz', new_quiz_path %>
        </li>
        <li class="<%= 'active' if current_page?(quizzes_path) %>">
          <%= link_to 'Take A Quiz', quizzes_path %>
        </li>
      </ul>

      <% if user_signed_in? %>
      <ul class='nav pull-right'>
        <div class='btn-group'>
          <button class='btn dropsit'>
            <%= image_tag gravatar_url(current_user, "18") %>
            <strong><%= link_to current_user.username, user_path(current_user) %></strong>
          </button>
          <button class='btn dropdown-toggle' data-toggle='dropdown'>
            <span class='caret'></span>
          </button>
          <ul class='dropdown-menu'>
            <li>
              <%= link_to 'Edit profile', edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </ul>
          <% else %>
          <ul class='nav pull-right'>
            <li class="signer">
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Login", new_user_session_path %>
            </li>
          </ul>
      <% end %>
        </div>
    </div>
  </div>
</div>


  <div class='container-fluid'>
    <% if notice || alert %>
      <div id='flash-msg' class='alert'>
        <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: name %>
        <%- end -%>
      </div>
    <% end %>


    <div class="row-fluid">
      <div class="span10 offset1">
        <%= yield %>

        <%= yield :extra_footer %>
      </div>
    </div>
  </div>

<!--   <div class="footer">
    <p>Kristina Durr</p>
  </div> -->
</body>

<script>
  $(function(){
    $('#flash-msg').fadeOut(3000);
  })
</script>
</html>

app/views/quizzes/_question_choice_fields.html.erb
<fieldset class='answer-set'>
  <%= f.input :option, label: 'Answer Option' %>
  <%= f.input :correct, label: false, :inline_label => true %>
  <%= f.hidden_field :_destroy %>
  <%= link_to '[remove]', '#', class: "remove_fields" %>
</fieldset>

app/views/quizzes/_question_fields.html.erb
<fieldset>
  <div class='question-answer-set'>
    <%= f.input :name, :label => 'Question' %>
    <%= f.hidden_field :_destroy %>
    <%= link_to '[remove]', '#', class: "remove_fields" %>
    <%= f.simple_fields_for :question_choices do |b| %>
      <%= render 'question_choice_fields', f: b %>
    <% end %>
    <%= link_to_add_fields 'Add Answer', f, :question_choices %><br />
  </div>
</fieldset>

app/views/quizzes/index.html.erb
<section class='container-fluid'>
  <%= search_form_for @q do |f| %>
    <div class="field pull-right">
      <%= f.text_field :title_cont %>
      <%= f.submit "Search", class: 'btn' %>
    </div>
  <% end %>

  <h4 class='quiz-take'>Take A Quiz!</h4>

  <% @quizzes.each do |quest| %>
  <% if !quest.private %>
      <% if current_user.present? && current_user.age >= quest.age_rating %>
        <div class='show-quiz span8 offset2'>
          <strong>Title:</strong>
          <div class='quiz-name'><%= quest.title %></div>
            <%= button_to 'Take this Quiz!', quiz_path(quest), 
                method: :get, class: 'take-me btn' %><br />
        </div>
      <% end %>
    <% end %>
  <% end %>

</section>

<%= content_for :extra_footer do %>
  <script>
    $(function() {
      $('.quiz-name').each(function() {
        if($(this).height() > 30)
          $(this).css('font-size', '12px');
      }); 
    });
  </script>
<% end %>

app/views/quizzes/new.html.erb
<section class='container-fluid newest-quiz'>
  <h4>Create A Quiz!</h4>

  <%= simple_form_for @quiz do |f| %>
  <fieldset class='quiz-creds'>
    <%= f.input :title %>
    <%= f.input :private, :label => false, :inline_label => true %>
    <%= f.input :age_rating, as: :radio_buttons, collection: [6, 10, 13, 17] %>
    <%= f.input :news_url, label: 'News sources' %>
  </fieldset>
    <%= f.simple_fields_for :questions do |q| %>
     <%= render 'question_fields', f: q %>
    <% end %><br />
    <%= link_to_add_fields 'Add Question', f, :questions %><br />
    <div id='sub'>
      <%= f.submit "Create Quiz!", class: 'btn' %>
    </div>
  <% end %>
</section>

<%= content_for :extra_footer do %>
  <script>
    $(function() {
      $('form').on('click', '.remove_fields', function(e) {
      $(this).prev('input[type=hidden]').val('1');
      $(this).closest('fieldset').hide();
      e.preventDefault();
      });
      
      $('form').on('click', '.add_fields', function(e) {
        var regexp, time;
        time = new Date().getTime();
        regexp = new RegExp($(this).data('id'), 'g');
        $(this).before($(this).data('fields').replace(regexp, time));
        $(this).addClass('added');
        e.preventDefault();
      });
    });
  </script>
<% end %>

app/views/quizzes/show.html.erb
<section class='container-fluid'>
  <div class="quiz-title">
    <h3>Take Quiz: <strong><%= @quiz.title %></strong></h3>
  </div>

  <div class="q_a_set">
    <%= simple_form_for([@quiz, @submission]) do |f|  %>
      <% @quiz.questions.each do |q| %>
      <div class='quest-name'>
        <strong>Question:</strong>
        <%= q.name %><br />
      </div>
        <div class='answer-field'>
          <%= f.simple_fields_for :answers do |a| %>
            <%= a.hidden_field :question_id, value: q.id %>
            <%= a.input :question_choice_id, as: :radio_buttons,
                collection: q.question_choices, label_method: :option, 
                label: false, item_wrapper_class: 'inline' %>
          <% end %>
        </div>
      <% end %>
      <%= f.submit "Submit", class: 'btn' %>
    <% end %>
    <% if @quiz.news_url.present? %>
      <div class='news-url'>
        <strong>Quiz sources: </strong><%= @quiz.news_url %>
      </div>
    <% end %>
  </div>
</section>

app/views/submissions/show.html.erb
<section class="container-fluid">
  <h1 class="your-score"><%= "You scored a #{@submission.result}%" %></h1>

  <h3 class="quiz-title">Quiz: <strong><%= @quiz.title %></strong></h3>
  <% @quiz.questions.each do |q| %>
    <div class="result-content">
      <strong><%= q.name %></strong><br />
      <% q.question_choices.each do |c| %>
        <% if c.correct == true %>
          <em><%= "*#{c.option}*" %></em><br />
        <% else %>
          <%= c.option %><br />
        <% end %>
      <% end %>
      <br>
    </div>
  <% end %>
  <div class='take-another'>
    <%= link_to 'Take another quiz!', quizzes_path %>
  </div>
</section>

app/views/users/index.html.erb
<br />
<div class='create-quiz'>
  <%= link_to 'Create a Quiz', new_quiz_path %>
</div>

app/views/users/show.html.erb
<section class='container-fluid user-profile'>

  <div class='span4 offset1 pull-left'>
    <%= image_tag gravatar_url(@user, "200") %><br />
  </div>

  <div class='user-info'>
    <strong>Name: </strong>
    <%= @user.first_name %>
    <%= @user.last_name[0] %>.<br />

    <strong>Age: </strong>
    <%= @user.age %><br />

    <strong>Username: </strong>
    <%= @user.username %><br />
  </div>

  <div class='quiz-stats'>
    <strong>Created Quizzes: </strong>
    <% if @user.quizzes.present? %>
      <div class='made-quizzes'>
        <% @user.quizzes.each do |q| %>
          <%= link_to q.title, quiz_path(q) %><br />
        <% end %>
    <% else %>
      <div><%= @user.username%> has not created any quizzes yet!</div>
    <% end %>
      </div><br />

    <strong>Taken Quizzes: </strong>
    <% if @user.submissions.present? %>
      <div class='taken-quizzes'>
      <% @user.submissions.each do |s| %>
        <%= link_to s.quiz.title, quiz_path(s.quiz) %>
        <%= s.result %>%<br />
      <% end %>
    <% else %>
      <div><%= @user.username %> has not taken any quizzes yet!</div>
    <% end %>
    </div>
  </div>

  <div class='offset1'>
    <%= link_to 'Take more quizzes!', quizzes_path %>
  </div>
</section>

app/views/welcome/index.html.erb
<section class='container-fluid'>
  <div class="welcome-image">
    <%= image_tag("https://lh6.googleusercontent.com/-anOOr9ADRbI/UmE_DL7xbdI/AAAAAAAAAls/gmlRo96aXcY/w441-h195-no/quizme.png") %>
  </div>

  <hr>

  <div class='first-description span3 offset2'>
    <%= image_tag("https://lh4.googleusercontent.com/-dlmaHVPSKl4/UmMripPfVGI/AAAAAAAAAp4/vxet-4lVH3s/w256-h160-no/newspaper_icon.png", size: "200") %>
    <p>
      <strong>Here at Quiz Me, create quizzes about current world news or any subject of your choice!</strong>
    </p>
  </div>

  <div class='second-description span3 offset2'>
    <%= image_tag("https://lh5.googleusercontent.com/-VU7kedagHYQ/UmWA4xLQ7iI/AAAAAAAAAqw/UNeFClRll9o/s512-no/check.png", size: "125", class: 'offset2') %>
    <p>
      <strong>Through your quizzes, spread knowledge of the world around us to loved ones and friends!</strong>
    </p>
  </div>
</section>